name: Check Release
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check_release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - node: "@fails-components/jupyter-applet-view"
            python: "fails_components_jupyter_applet_view"
            shortname: "applet-view"
          - node: "@fails-components/jupyter-filesystem-extension"
            python: "fails_components_jupyter_filesystem_extension"
            shortname: "filesystem-extension"
          - node: "@fails-components/jupyter-interceptor"
            python: "fails_components_jupyter_interceptor"
            shortname: "interceptor"
          - node: "@fails-components/jupyter-launcher"
            python: "fails_components_jupyter_launcher"
            shortname: "launcher"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      - name: Check Release
        uses: jupyter-server/jupyter_releaser/.github/actions/check-release@v2
        with:

          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Distributions
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.python }}-releaser-dist-${{ github.run_number }}
          path: .jupyter_releaser_checkout/dist
